# Generated by AESTD, Minecraft 1.14

scoreboard players set @s aestd.random.max 2
function aestd:math/random

execute if score @s aestd.random matches 0 run data modify entity @s Offers.Recipes append value {buy:{id:"minecraft:book",Count:13b},sell:{id:"minecraft:emerald",Count:2b}}
execute if score @s aestd.random matches 1 run data modify entity @s Offers.Recipes append value {buy:{id:"minecraft:emerald",Count:1b},sell:{id:"minecraft:nether_quartz",Count:6b}}

scoreboard players set @s aestd.random.max 2
function aestd:math/random

execute if score @s aestd.random matches 0 run data modify entity @s Offers.Recipes append value {buy:{id:"minecraft:emerald",Count:9b},sell:{id:"minecraft:potion",Count:1b,tag:{Potion:"healing"}}}
execute if score @s aestd.random matches 1 run data modify entity @s Offers.Recipes append value {buy:{id:"minecraft:clock",Count:8b,tag:{cvm_item:{id:"topaz"},CustomModelData:1512004,display:{Name:'{"italic":false,"translate":"cvm.item.topaz"}'}}},sell:{id:"minecraft:emerald",Count:3b}}

scoreboard players add @s aestd.vt.total_t 2
