# Generated by AESTD, Minecraft 18w50a
# Type: entity, name: high_priest

summon minecraft:villager ~ ~ ~ {Attributes:[{Name:"generic.maxHealth",Base:36d}],CustomName:"{\"translate\":\"cvm.entity.high_priest\"}",DeathLootTable:"cvm:entities/high_priest",Health:36f,Tags:["cvm.entity.checked","cvm.mobs.high_priest","cvm.mobs.changed"],VillagerData:{level:1,profession:"minecraft:cleric"},Xp:1}
