# Generated by AESTD, Minecraft 18w50a
# Type: entity, name: undead_caster

data merge entity @s {ArmorDropChances:[0f,0f,0f,0f],ArmorItems:[{id:"minecraft:chainmail_boots",Count:1b},{id:"minecraft:chainmail_leggings",Count:1b},{id:"minecraft:chainmail_chestplate",Count:1b},{id:"minecraft:chainmail_helmet",Count:1b}],CustomName:"{\"translate\":\"cvm.entity.undead_caster\"}",DeathLootTable:"cvm:entities/undead_caster",HandItems:[{id:"minecraft:stick",Count:1b,tag:{display:{Name:"{\"translate\":\"cvm.item.magic_wand\"}"}}}],Tags:["cvm.entity.checked","cvm.mobs.undead_caster","cvm.mobs.changed"]}
