# Generated by AESTD, Minecraft 18w50a
# Type: entity, name: possessed_armor

summon minecraft:zombie ~ ~ ~ {ArmorDropChances:[0f,0f,0f,0f],ArmorItems:[{id:"minecraft:iron_boots",Count:1b},{id:"minecraft:iron_leggings",Count:1b},{id:"minecraft:iron_chestplate",Count:1b},{id:"minecraft:iron_helmet",Count:1b}],Attributes:[{Name:"generic.maxHealth",Base:40d}],CustomName:"{\"translate\":\"cvm.mobs.possessed_armor\"}",DeathLootTable:"cvm:entity/possessed_armor",Health:40f,isBaby:0,Silent:1,Tags:["cvm.entity.checked","cvm.mobs.possessed_armor","cvm.mobs.changed","cvm.mobs.invisible"]}
