# Generated by AESTD, Minecraft 18w50a
# Type: entity, name: ender_eye

give @s minecraft:zombie_spawn_egg{SpawnData:{ArmorDropChances:[0f,0f,0f,0f],ArmorItems:[{id:"minecraft:air"},{id:"minecraft:air"},{id:"minecraft:air"},{id:"minecraft:player_head",Count:1b,tag:{SkullOwner:{Id:"36122cdc-6c97-4b97-990a-ef4df57db922",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGFhOGZjOGRlNjQxN2I0OGQ0OGM4MGI0NDNjZjUzMjZlM2Q5ZGE0ZGJlOWIyNWZjZDQ5NTQ5ZDk2MTY4ZmMwIn19fQ=="}]}}}}],CustomName:"{\"translate\":\"cvm.entity.ender_eye\"}",DeathLootTable:"cvm:entity/ender_eye",Silent:1,Tags:["cvm.entity.checked","cvm.mobs.ender_eye","cvm.mobs.changed","cvm.mobs.invisible"]}}
