# Generated by AESTD, Minecraft 18w50a
# Type: entity, name: villager_warrior

data merge entity @s {Attributes:[{Name:"generic.maxHealth",Base:30d}],CustomName:"{\"translate\":\"cvm.entity.villager_warrior\"}",DeathLootTable:"cvm:entities/villager_warrior",Health:30f,Tags:["cvm.entity.checked","cvm.mobs.villager_warrior","cvm.mobs.changed"],VillagerData:{level:1,profession:"minecraft:none"}}
