# Written by Aeldrion, Minecraft 1.14
# Delete trades that were generated by Minecraft by default

execute if score @s aestd.vt.total_t matches 1 run data remove entity @s Offers.Recipes[1]
execute if score @s aestd.vt.total_t matches 2 run data remove entity @s Offers.Recipes[2]
execute if score @s aestd.vt.total_t matches 3 run data remove entity @s Offers.Recipes[3]
execute if score @s aestd.vt.total_t matches 4 run data remove entity @s Offers.Recipes[4]
execute if score @s aestd.vt.total_t matches 5 run data remove entity @s Offers.Recipes[5]
execute if score @s aestd.vt.total_t matches 6 run data remove entity @s Offers.Recipes[6]
execute if score @s aestd.vt.total_t matches 7 run data remove entity @s Offers.Recipes[7]
execute if score @s aestd.vt.total_t matches 8 run data remove entity @s Offers.Recipes[8]
execute if score @s aestd.vt.total_t matches 9 run data remove entity @s Offers.Recipes[9]
execute if score @s aestd.vt.total_t matches 10 run data remove entity @s Offers.Recipes[10]
execute if score @s aestd.vt.total_t matches 11 run data remove entity @s Offers.Recipes[11]
execute if score @s aestd.vt.total_t matches 12 run data remove entity @s Offers.Recipes[12]
execute if score @s aestd.vt.total_t matches 13 run data remove entity @s Offers.Recipes[13]
execute if score @s aestd.vt.total_t matches 14 run data remove entity @s Offers.Recipes[14]
execute if score @s aestd.vt.total_t matches 15 run data remove entity @s Offers.Recipes[15]
execute if score @s aestd.vt.total_t matches 16 run data remove entity @s Offers.Recipes[16]
execute if score @s aestd.vt.total_t matches 17 run data remove entity @s Offers.Recipes[17]
execute if score @s aestd.vt.total_t matches 18 run data remove entity @s Offers.Recipes[18]
execute if score @s aestd.vt.total_t matches 19 run data remove entity @s Offers.Recipes[19]
execute if score @s aestd.vt.total_t matches 20 run data remove entity @s Offers.Recipes[20]

execute if score @s aestd.vt.total_t matches 1 if data entity @s Offers.Recipes[1] run function cvm:entity/villager_warrior/behavior/trades/delete_default_trades
execute if score @s aestd.vt.total_t matches 2 if data entity @s Offers.Recipes[2] run function cvm:entity/villager_warrior/behavior/trades/delete_default_trades
execute if score @s aestd.vt.total_t matches 3 if data entity @s Offers.Recipes[3] run function cvm:entity/villager_warrior/behavior/trades/delete_default_trades
execute if score @s aestd.vt.total_t matches 4 if data entity @s Offers.Recipes[4] run function cvm:entity/villager_warrior/behavior/trades/delete_default_trades
execute if score @s aestd.vt.total_t matches 5 if data entity @s Offers.Recipes[5] run function cvm:entity/villager_warrior/behavior/trades/delete_default_trades
execute if score @s aestd.vt.total_t matches 6 if data entity @s Offers.Recipes[6] run function cvm:entity/villager_warrior/behavior/trades/delete_default_trades
execute if score @s aestd.vt.total_t matches 7 if data entity @s Offers.Recipes[7] run function cvm:entity/villager_warrior/behavior/trades/delete_default_trades
execute if score @s aestd.vt.total_t matches 8 if data entity @s Offers.Recipes[8] run function cvm:entity/villager_warrior/behavior/trades/delete_default_trades
execute if score @s aestd.vt.total_t matches 9 if data entity @s Offers.Recipes[9] run function cvm:entity/villager_warrior/behavior/trades/delete_default_trades
execute if score @s aestd.vt.total_t matches 10 if data entity @s Offers.Recipes[10] run function cvm:entity/villager_warrior/behavior/trades/delete_default_trades
execute if score @s aestd.vt.total_t matches 11 if data entity @s Offers.Recipes[11] run function cvm:entity/villager_warrior/behavior/trades/delete_default_trades
execute if score @s aestd.vt.total_t matches 12 if data entity @s Offers.Recipes[12] run function cvm:entity/villager_warrior/behavior/trades/delete_default_trades
execute if score @s aestd.vt.total_t matches 13 if data entity @s Offers.Recipes[13] run function cvm:entity/villager_warrior/behavior/trades/delete_default_trades
execute if score @s aestd.vt.total_t matches 14 if data entity @s Offers.Recipes[14] run function cvm:entity/villager_warrior/behavior/trades/delete_default_trades
execute if score @s aestd.vt.total_t matches 15 if data entity @s Offers.Recipes[15] run function cvm:entity/villager_warrior/behavior/trades/delete_default_trades
execute if score @s aestd.vt.total_t matches 16 if data entity @s Offers.Recipes[16] run function cvm:entity/villager_warrior/behavior/trades/delete_default_trades
execute if score @s aestd.vt.total_t matches 17 if data entity @s Offers.Recipes[17] run function cvm:entity/villager_warrior/behavior/trades/delete_default_trades
execute if score @s aestd.vt.total_t matches 18 if data entity @s Offers.Recipes[18] run function cvm:entity/villager_warrior/behavior/trades/delete_default_trades
execute if score @s aestd.vt.total_t matches 19 if data entity @s Offers.Recipes[19] run function cvm:entity/villager_warrior/behavior/trades/delete_default_trades
execute if score @s aestd.vt.total_t matches 20 if data entity @s Offers.Recipes[20] run function cvm:entity/villager_warrior/behavior/trades/delete_default_trades

