# Generated by AESTD, Minecraft 1.14

function cvm:entity/villager_warrior/behavior/trades/delete_default_trades

data modify entity @s Offers.Recipes append value {buy:{id:"minecraft:emerald",Count:34b},sell:{id:"minecraft:trident",Count:1b}}

scoreboard players set @s aestd.random.max 2
function aestd:math/random

execute if score @s aestd.random matches 0 run data modify entity @s Offers.Recipes append value {buy:{id:"minecraft:emerald",Count:4b},sell:{id:"minecraft:tipped_arrow",Count:12b,tag:{Potion:"minecraft:strong_harming"}}}

scoreboard players add @s aestd.vt.total_t 1
scoreboard players add @s[scores={aestd.random=0}] aestd.vt.total_t 1
