# Generated by AESTD, Minecraft 1.14

function cvm:entity/villager_warrior/behavior/trades/delete_default_trades

scoreboard players set @s aestd.random.max 3
function aestd:math/random

execute if score @s aestd.random matches 0 run data modify entity @s Offers.Recipes append value {buy:{id:"minecraft:golden_apple",Count:1b},sell:{id:"minecraft:emerald",Count:1b}}
execute if score @s aestd.random matches 1 run data modify entity @s Offers.Recipes append value {buy:{id:"minecraft:emerald",Count:2b},sell:{id:"minecraft:arrow",Count:16b}}
execute if score @s aestd.random matches 2 run data modify entity @s Offers.Recipes append value {buy:{id:"minecraft:book",Count:1b},buyB:{id:"minecraft:emerald",Count:17b},sell:{id:"minecraft:enchanted_book",Count:1b,tag:{StoredEnchantments:[{id:"minecraft:smite",lvl:4s}]}}}

scoreboard players set @s aestd.random.max 3
function aestd:math/random

execute if score @s aestd.random matches 0 run data modify entity @s Offers.Recipes append value {buy:{id:"minecraft:emerald",Count:11b},sell:{id:"minecraft:enchanted_book",Count:1b,tag:{StoredEnchantments:[{id:"minecraft:sharpness",lvl:2s}]}}}
execute if score @s aestd.random matches 1 run data modify entity @s Offers.Recipes append value {buy:{id:"minecraft:emerald",Count:5b},sell:{id:"minecraft:golden_apple",Count:1b}}
execute if score @s aestd.random matches 2 run data modify entity @s Offers.Recipes append value {buy:{id:"minecraft:emerald",Count:8b},sell:{id:"minecraft:crossbow",Count:1b}}

scoreboard players add @s aestd.vt.total_t 2
