# Generated by AESTD, Minecraft 1.14

scoreboard players set @s aestd.random.max 3
function aestd:math/random

execute if score @s aestd.random matches 0 run data modify entity @s Offers.Recipes append value {buy:{id:"minecraft:golden_apple",Count:1b},sell:{id:"minecraft:emerald",Count:1b}}
execute if score @s aestd.random matches 1 run data modify entity @s Offers.Recipes append value {buy:{id:"minecraft:emerald",Count:2b},sell:{id:"minecraft:arrow",Count:16b}}
execute if score @s aestd.random matches 2 run data modify entity @s Offers.Recipes append value {buy:{id:"minecraft:book",Count:1b},buyB:{id:"minecraft:emerald",Count:17b},sell:{id:"minecraft:enchanted_book",Count:b,tag:{StoredEnchantments:[{id:"minecraft:smite",lvl:4s}]}}}
