# Generated by AESTD, Minecraft 1.14

scoreboard players set @s aestd.random.max 1
function aestd:math/random

execute if score @s aestd.random matches 0 run data modify entity @s Offers.Recipes append value {buy:{id:"minecraft:emerald",Count:34b},sell:{id:"minecraft:trident",Count:1b}}
