# Generated by AESTD, Minecraft 1.14

function cvm:entity/villager_warrior/behavior/trades/delete_default_trades

scoreboard players set @s aestd.random.max 3
function aestd:math/random

execute if score @s aestd.random matches 0 run data modify entity @s Offers.Recipes append value {buy:{id:"minecraft:emerald",Count:13b},sell:{id:"minecraft:diamond_sword",Count:1b}}
execute if score @s aestd.random matches 1 run data modify entity @s Offers.Recipes append value {buy:{id:"minecraft:emerald",Count:2b},sell:{id:"minecraft:ender_pearl",Count:13b}}
execute if score @s aestd.random matches 2 run data modify entity @s Offers.Recipes append value {buy:{id:"minecraft:diamond_sword",Count:1b},buyB:{id:"minecraft:emerald",Count:19b},sell:{id:"minecraft:diamond_sword",Count:1b,tag:{Enchantments:[{id:"minecraft:sharpness",lvl:4s},{id:"minecraft:knockback",lvl:3s}]}}}

function aestd:math/random

execute if score @s aestd.random matches 0..1 run data modify entity @s Offers.Recipes append value {buy:{id:"minecraft:book",Count:1b,tag:{cvm_item:{id:"blessed_book",StoredBlessing:"frostburn"},CustomModelData:1512001,display:{Lore:['{"translate":"cvm.blessing.frostburn","italic":false,"color":"aqua"}'],Name:'{"italic":false,"color":"gold","translate":"cvm.item.blessed_book"}'}}},sell:{id:"minecraft:emerald",Count:10b}}
execute if score @s aestd.random matches 1..2 run data modify entity @s Offers.Recipes append value {buy:{id:"minecraft:emerald",Count:12b},sell:{id:"minecraft:iron_sword",Count:1b,tag:{display:{Name:'{"translate":"cvm.item.testificatex","italic":false,"color":"gold"}'},CustomModelData:1512004,cvm_item:{id:"testificatex"}}}}

scoreboard players add @s aestd.vt.total_t 2
scoreboard players add @s[scores={aestd.random=1}] aestd.vt.total_t 1
