# Generated by AESTD, Minecraft 1.14

scoreboard players set @s aestd.random.max 3
function aestd:math/random

execute if score @s aestd.random matches 0 run data modify entity @s Offers.Recipes append value {buy:{id:"minecraft:emerald",Count:13b},sell:{id:"minecraft:diamond_sword",Count:1b}}
execute if score @s aestd.random matches 1 run data modify entity @s Offers.Recipes append value {buy:{id:"minecraft:emerald",Count:2b},sell:{id:"minecraft:ender_pearl",Count:13b}}
execute if score @s aestd.random matches 2 run data modify entity @s Offers.Recipes append value {buy:{id:"minecraft:diamond_sword",Count:1b},buyB:{id:"minecraft:emerald",Count:19b},sell:{id:"minecraft:diamond_sword",Count:1b,tag:{Enchantments:[{id:"minecraft:sharpness",lvl:4s},{id:"minecraft:knockback",lvl:3s}]}}}
