# Generated by AESTD, Minecraft 18w50a
# Type: entity, name: riverbeast

summon minecraft:skeleton ~ ~ ~ {ArmorDropChances:[0f,0f,0f,0f],ArmorItems:[{id:"minecraft:air"},{id:"minecraft:air"},{id:"minecraft:leather_chestplate",Count:1b,tag:{display:{color:65535}}},{id:"minecraft:sea_lantern",Count:1b}],CustomName:"{\"translate\":\"cvm.entity.riverbeast\"}",DeathLootTable:"cvm:entities/riverbeast",NoGravity:1,Silent:1,Tags:["cvm.entity.checked","cvm.mobs.riverbeast","cvm.mobs.changed","cvm.mobs.invisible"]}
